version: 2.1
orbs:
  terraform: circleci/terraform@3.2.0
jobs:
  provision-terraform:
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: 0.14.2
      - terraform/fmt:
          path: ./terraform
      - terraform/validate:
          path: ./terraform
      - terraform/init:
          path: ./terraform

workflows:
  s3:
    jobs:
      - provision-terraform:
          context: playground-terraform
