version: 2.1
jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      - run:
          name: terraform init & plan
          command: |
            cd terraform
            terraform init -input=false
            terraform plan -out tfapply -lock=false
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  provision-terraform:
    jobs:
      - plan-apply
      # - hold-apply:
      #     type: approval
      #     requires:
      #       - plan-apply
      # - apply:
      #     requires:
      #       - hold-apply
      # - plan-destroy:
      #     requires:
      #       - apply
      # - hold-destroy:
      #     type: approval
      #     requires:
      #       - plan-destroy
      # - destroy:
      #     requires:
      #       - hold-destroy
