version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-s3: circleci/aws-s3@3.1.1

jobs:
  provision-s3:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            cd terraform
            terraform init -input=false
            terraform plan -out tfapply
      - run:
          name: terraform apply
          command: |
            cd terraform
            terraform apply -auto-approve tfapply

  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
          name: Build
      - persist_to_workspace:
          root: .
          paths:
            - build
  sync:
    executor: node/default
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: build
          to: s3://playground-react-s3

workflows:
  version: 2
  provision-terraform:
    jobs:
      - provision-s3:
          context:
            - playground-terraform
            - playground-aws
      - build
      - sync:
          requires:
            - provision-s3
            - build
          context:
            - playground-aws
